### ISSUE TITLE
Pop-up only shows once

### ISSUE THREAD

**Issue by Sven-vh** [google-unity/in-app-review#5]
Hi, I'm having an issue where the pop-up only shows once when using a fresh Google account.
If I cancel the review and click on the review button again I get nothing, it doesn't even go to the Google Play Store link.
I've attached the Logcat.
The successful click is around ``13:09:10.811``
And the other tries are around:
13:09:19.142
13:09:21.428
[logcat.txt](https://github.com/google-unity/in-app-review/files/14179353/logcat.txt)

If I switch to another Google account in the Google Play Store app, the same happens again. I get a window once, but after that nothing. Now this is fine, but only if the direct link works the 2nd time I press or when the pop-up doesn't show.

**Comment by aprius** [comment]
@HyTap https://developer.android.com/guide/playcore/in-app-review?#quotas

To provide a great user experience, Google Play enforces a time-bound quota on how often a user can be shown the review dialog. Because of this quota, calling the launchReviewFlow method more than once during a short period of time (for example, less than a month) might not always display a dialog.

**Comment by Sven-vh** [comment]
I guess that is fine, but is there still a way to know if the user actually got the dialog?
Because if not, I can just send them to the Google Play Store page.

**Comment by aprius** [comment]
You can send users to the Google Play Store page as long as the launchFlowOperation.Error status is not NoError

You can see the example code in the ReadMe section

![image](https://github.com/google-unity/in-app-review/assets/44673303/d2028af5-5164-46c1-bd20-bdfc64c91033)
